# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stock_exchange.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x14stock_exchange.proto\x12\x0estock_exchange\"\x07\n\x05\x45mpty\"\x1d\n\nSubRequest\x12\x0f\n\x07symbols\x18\x01 \x03(\t\":\n\x13SubPctChangeRequest\x12\x0f\n\x07symbols\x18\x01 \x03(\t\x12\x12\n\npct_change\x18\x02 \x01(\x01\"(\n\x05Offer\x12\r\n\x05price\x18\x01 \x01(\x01\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"\x83\x02\n\tStockData\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x14\n\x0c\x63ompany_name\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x01\x12\x0e\n\x06volume\x18\x04 \x01(\x05\x12\x11\n\ttimestamp\x18\x05 \x01(\x03\x12.\n\x0f\x62\x65st_bid_offers\x18\x06 \x03(\x0b\x32\x15.stock_exchange.Offer\x12.\n\x0f\x62\x65st_ask_offers\x18\x07 \x03(\x0b\x32\x15.stock_exchange.Offer\x12*\n\x08\x63urrency\x18\x08 \x01(\x0e\x32\x18.stock_exchange.Currency\x12\x12\n\npct_change\x18\t \x01(\x01\"\x96\x01\n\x11StockDataResponse\x12\x39\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32+.stock_exchange.StockDataResponse.DataEntry\x1a\x46\n\tDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12(\n\x05value\x18\x02 \x01(\x0b\x32\x19.stock_exchange.StockData:\x02\x38\x01*.\n\x08\x43urrency\x12\x07\n\x03USD\x10\x00\x12\x07\n\x03\x45UR\x10\x01\x12\x07\n\x03GBP\x10\x02\x12\x07\n\x03JPY\x10\x03\x32\xf5\x01\n\rStockExchange\x12L\n\tSubscribe\x12\x1a.stock_exchange.SubRequest\x1a!.stock_exchange.StockDataResponse0\x01\x12`\n\x14SubscribeOnPctChange\x12#.stock_exchange.SubPctChangeRequest\x1a!.stock_exchange.StockDataResponse0\x01\x12\x34\n\x04Ping\x12\x15.stock_exchange.Empty\x1a\x15.stock_exchange.Emptyb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stock_exchange_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _STOCKDATARESPONSE_DATAENTRY._options = None
    _STOCKDATARESPONSE_DATAENTRY._serialized_options = b'8\001'
    _CURRENCY._serialized_start = 597
    _CURRENCY._serialized_end = 643
    _EMPTY._serialized_start = 40
    _EMPTY._serialized_end = 47
    _SUBREQUEST._serialized_start = 49
    _SUBREQUEST._serialized_end = 78
    _SUBPCTCHANGEREQUEST._serialized_start = 80
    _SUBPCTCHANGEREQUEST._serialized_end = 138
    _OFFER._serialized_start = 140
    _OFFER._serialized_end = 180
    _STOCKDATA._serialized_start = 183
    _STOCKDATA._serialized_end = 442
    _STOCKDATARESPONSE._serialized_start = 445
    _STOCKDATARESPONSE._serialized_end = 595
    _STOCKDATARESPONSE_DATAENTRY._serialized_start = 525
    _STOCKDATARESPONSE_DATAENTRY._serialized_end = 595
    _STOCKEXCHANGE._serialized_start = 646
    _STOCKEXCHANGE._serialized_end = 891
# @@protoc_insertion_point(module_scope)
